### ISSUE TITLE
Doesn't compile with -std=c++11 and/or Boost 1.66+

### ISSUE THREAD

**Issue by diizzyy** [arvidn/libtorrent-webui#7]
@arvidn 

```
clang-linux.compile.c++.without-pch libtorrent-webui/bin/clang-gnu-linux-4.0.0/debug/crypto-openssl/link-static/src/deluge.o
libtorrent-webui/src/deluge.cpp:67:4: error: no matching constructor for initialization of 'boost::asio::ssl::context'
        , m_context(m_ios, boost::asio::ssl::context::sslv23)
          ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/ssl/impl/context.ipp:63:10: note: candidate constructor not viable: requires single argument 'm', but 2 arguments were provided
context::context(context::method m)
         ^
/usr/local/include/boost/asio/ssl/impl/context.ipp:326:10: note: candidate constructor not viable: requires single argument 'other', but 2 arguments were provided
context::context(context&& other)
         ^
/usr/local/include/boost/asio/ssl/context.hpp:36:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
class context
      ^
libtorrent-webui/src/deluge.cpp:573:16: warning: unused variable 'diff' [-Wunused-variable]
        rtok_t const* diff = skip_item(keys);
                      ^
libtorrent-webui/src/deluge.cpp:753:6: warning: 'paused' is deprecated [-Wdeprecated-declarations]
                        p.paused = options[1].boolean(buf);
                          ^
libtorrent/include/libtorrent/add_torrent_params.hpp:424:34: note: 'paused' has been explicitly marked deprecated here
                bool TORRENT_DEPRECATED_MEMBER paused;
                                               ^
libtorrent-webui/src/deluge.cpp:854:7: warning: unused variable 'need_term' [-Wunused-variable]
        bool need_term = out.append_dict(num_keys);
             ^
3 warnings and 1 error generated.
```

OS: FreeBSD 11.1
Seems similar to: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=224181
Version of libtorrent is 1.1.6 and the rest is git master

**Comment by arvidn** [comment]
there is a branch where I've started the conversion to C++11 and libtorrent master. But I haven't had the time to complete it.

https://github.com/arvidn/libtorrent-webui/tree/cpp11-upgrade

Patches are welcome!

As for libtorrent failing to build with boost 1.66, that's been fixed in the stable branch ``RC_1_1`` (of libtorrent) and will be released as 1.1.7 soon. There are a few more known issues I would like to resolve first though. (specifically [this](https://github.com/arvidn/libtorrent/issues/2674), [this](https://github.com/arvidn/libtorrent/pull/2815) and [this](https://github.com/arvidn/libtorrent/issues/2724)).

Any help is appreciated! especially with the [1.1.6 issues](https://github.com/arvidn/libtorrent/milestone/7).

**Comment by diizzyy** [comment]
Hmm, I tried and that branch seems to introduce even more breakage than master at least using clang. Unfortunately my knowledge about C++ is very limited so I can't really help out but thanks for the heads up about current status of the project.

**Comment by diizzyy** [comment]
I think we can close this by now, if anyone else wants to hack on it they can open a new issue / PR.
